name: Sync Releases

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
